name: CI-CD1
on:
  push:
    branches:
      - main  //자동으로 업데이트될 브랜치
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04  //우분투 버젼
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP_1 }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/nutrient
            # git config --global --add safe.directory /home/ubuntu/nutrient
            sudo git pull
            # sudo npm update
            sudo npm install
            sudo pm2 reload all
